name: clock_it
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.5
  stream_transform: ^2.0.0
  google_nav_bar: ^5.0.6
  flutter_slidable: ^1.2.0
  percent_indicator: ^3.4.0

  #ObjectBox
  objectbox: ^2.1.0
  objectbox_flutter_libs: any

  # Emoji Keyboard
  emoji_picker_flutter: ^1.6.1

  # Calendar widget
  calendar_date_picker2: ^0.5.2
  flutter_colorpicker: ^1.0.3
  chips_choice: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  #Objectbox
  build_runner: ^2.1.11
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - images/